baseurl: "/Imvertor-algemeen"
# apiname: "BRK Bevragen"
url: "http://localhost:4000"
# nav is t.b.v. generatie side-navigation menu.
# Een 'title' zonder path of url genereert slechts een kopje.
# 'path' vormt tezamen met de baseurl de url waarmee de 'href' wordt gevuld.
# Indien een 'url' voorradig dan wordt daarmee de 'href' gevuld en dient het path slechts om te bepalen welke link active is.
# 'target: blank' zorgt er voor dat de link in een nieuw tabblad wordt geöpend.
nav:
  - title: Imvertor
    subnav:
      - title: Introductie
        path: /
      - title: Gebruikende organisaties
        path: /gebruikende-organisaties
  - title: Imvertor onderdelen
    subnav:
      - title: Imvertor onderwerp 1
        path: /imvertor-onderwerp-1
      - title: Imvertor onderwerp 2
        path: /imvertor-onderwerp-2
plugins:
  - jekyll-redirect-from
  - jekyll-remote-theme
  
remote_theme: VNG-Realisatie/jekyll-theme-haal-centraal

# remote_theme: melsk-r/Imvertor-jekyll-theme

github: melsk-r/Imvertor-algemeen

theme: jekyll-theme-time-machine

project_name: /Imvertor-algemeen
